name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9']
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/index.html
  coverage:
    name: Coverage
    needs: test
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install beautifulsoup4
          python -m pip install lxml
      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - name: Get value
        run: |
          export TOTAL=$(python -c "from bs4 import BeautifulSoup; path = 'index.html'; file = open(path, 'r'); index = file.read(); Parse = BeautifulSoup(index, 'lxml'); val = Parse.main.table.tfoot.select('td:nth-of-type(5)')[0].text; print(val)")
          echo "Total=$TOTAL"